### ISSUE TITLE
Exception during upload

### ISSUE THREAD

**Issue by AlexejHirsch** [wargamer/BS.Output.VSO#3]
----------------------------------------------
Bug Shooting Version: 2.17.0.845
OS: Microsoft Windows 10 Pro
----------------------------------------------
Exception:
Microsoft.VisualStudio.Services.Common.VssServiceException

TF237082: The file you are trying to upload exceeds the supported file upload size (60.000 MB(s)). Instead of uploading the file, add the file to version control or to the team project web site, and then link the file to the work item.

  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at BS.Output.VSO.Services.VSOClient.<CreateBug>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at BS.Output.VSO.OutputAddIn.<Send>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at BS.Plugin.V3.Output.OutputPlugin`1.VB$StateMachine_32_Generic_Send.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at zkl7CHaRvrofh0aLRWc.NBvPhPaLC3Rgr0Z5oym.VB$StateMachine_27_Send.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at fTiuGPZNErbAHjVn2Uh.opw6b3ZAGWfB9AIHy0B.VB$StateMachine_107_SendToOutput.MoveNext()

**Comment by wargamer** [comment]
Thank you for reporting this.
It happens when long Series are attached to a VSTS bug.
At the moment I'm not sure which API to call to prevent this so I'll have to look into it. That might not be for a while though.

**Comment by wargamer** [comment]
With the release of version 1.3.0 of this plug-in, images are now compressed to allow for Series to be uploaded to Azure Devops.
Plus simple exception handling has been added so that the upload fails, a message box is shown and the exception is contained by the plug-in.
